### ISSUE TITLE
Feature/UPOS combinations that should be ruled out across English treebanks

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#549]
We should tighten up the allowed combinations in the [validator settings](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_feature.pl?lcode=en). Several that stand out as problematic but will require data fixes:

- [x] `Case=Nom` in LinES: https://github.com/UniversalDependencies/UD_English-LinES/issues/17
- [x] `Degree` for non-`ADJ`/`ADV` e.g. [this query](https://universal.grew.fr/?custom=66f00ffae8e0f) (first identified in https://github.com/UniversalDependencies/docs/issues/1055) (GUM*, LiNES, PUD: fixed)
- [x] `Gender` for non-`PRON` words in ParTUT: https://github.com/UniversalDependencies/UD_English-ParTUT/issues/2
- [x] `Number` e.g. [this query](https://universal.grew.fr/?custom=66f00ef475821): UniversalDependencies/UD_English-ParTUT#3
- [x] `PronType` for `NUM`, `SCONJ` e.g. [this query](https://universal.grew.fr/?custom=66f00f764896b) (GUM*, LinES, PUD: fixed)

(Manually fixed some `Definite`, `Tense`, `VerbForm` issues in LinES and PUD)

**Comment by amir-zeldes** [comment]
Fixed the GUM PronType and Degree issues upstream, thanks

**Comment by nschneid** [comment]
In the validator I've disabled PronType for NUM/SCONJ, and limited Case=Nom to PRON. I think all the corpora are up to date with these changes (GUM changes are upstream).

**Comment by LarsAhrenberg** [comment]
The validator for English does not allow the negative twopart conjunction _neither - nor_ to be annotated as Negative, neither by PronType nor by Polarity as these features are disallowed for upos CCONJ. What is the reasoning behind that decision?

**Comment by nschneid** [comment]
It's a good question—I don't know if it has been discussed. https://universaldependencies.org/en/feat/Polarity.html doesn't mention CCONJ one way or the other, and I don't see it on the universal documentation pages either. A CCONJ is a function word, but is it "pronoun-like"?

**Comment by nschneid** [comment]
Opened an issue for wider discussion: UniversalDependencies/docs#1056

**Comment by nschneid** [comment]
`Degree` is now limited to ADJ and ADV.

**Comment by nschneid** [comment]
AFAICT the only remaining issues now are `Gender` and `Number` in ParTUT.

**Comment by nschneid** [comment]
Validator configuration now updated for all these features. There is a pending decision about negative CCONJ (https://github.com/UniversalDependencies/docs#1056). Beyond that, LinES still has some validation issues. Can't tell for sure about GUM* because changes are upstream.

**Comment by amir-zeldes** [comment]
OK, I pushed a preview version to UD dev (just GUM, no reddit/GENTLE) so you can take a look, I think everything we discussed is implemented.

**Comment by nschneid** [comment]
Still some errors for GENTLE: http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_English-GENTLE

**Comment by amir-zeldes** [comment]
> no reddit/GENTLE

^
